### ISSUE TITLE
10 - Pantalla de bienvenida

### ISSUE THREAD

**Issue by ivanchenoweth** [REUBATCODE/UP-HEALTH#2]
HTML

**Comment by ivanchenoweth** [comment]
Ejemplo de LOGIN con sesiones
https://www.w3schools.blog/php-program-to-create-login-and-logout-using-sessions

**Comment by AngelDabnee** [comment]
https://www.rutinaejercicios.com/gimnasio.html basaremos nuestra idea en esta página

**Comment by ivanchenoweth** [comment]
> https://www.rutinaejercicios.com/gimnasio.html basaremos nuestra idea en esta página

Suena muy bien. Les recuerdo al mantainer @REUBATCODE que haga  el proyecto y el milestone para asignarse los issues

**Comment by ivanchenoweth** [comment]
- Diseñen el esqueleto lo antes posible para que su estructura tome sentido 
https://www.w3schools.com/w3css/w3css_web_tmp_catering.asp

**Comment by ivanchenoweth** [comment]
Que impedimentos ha habido para elaborar este issue?... ya tiene 5 dias

**Comment by ivanchenoweth** [comment]
Tu puedes crear la rama que tu quieras, con la base que tu quieras, cuando tu quieras.
Normalmente como bena practica, se debe crear una rama por cada issue
https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-a-branch-for-an-issue

**Comment by REUBATCODE** [comment]
Ya se realizó el primer commit de la rama de este Issue, pero necesito borrar los archivos del primerísimo primer commit del repo, necesito asistencia para ello!

**Comment by ivanchenoweth** [comment]
No se ha terminado, algun impedimento?
