### ISSUE TITLE
Entrega de la Actividad 1.1 de integradora - Planeacion 

### ISSUE THREAD

**Issue by ivanchenoweth** [REUBATCODE/UP-HEALTH#3]
Entregará propuesta de solución basado en un caso de estudio que contenga:
● Identificación del problema o necesidad a atender.
● Propuesta de solución del proyecto.
● Justificación de la propuesta de solución.
● Plan del proyecto (Cronograma de actividades) ....

Subirlo a classroom

**Comment by ivanchenoweth** [comment]
1.- Identificación del problema o necesidad a atender (Elevator pitch).
https://retos-directivos.eae.es/elevator-pitch-ejemplos-y-consejos-practicos-para-elaborarlo
2.-   Propuesta de solución del proyecto (pitch deck):
https://piktochart.com/blog/startup-pitch-decks-what-you-can-learn
3.- Justificacion de la propuesta de solucion:
 Agile Minimo producto viable, stack de tecnologia.
4.-   Plan del proyecto (Cronograma de actividades) 
Agil (historias de usuario)

**Comment by ivanchenoweth** [comment]
El Plan del proyecto (Cronograma de actividades), debe inclur 

- Calendario de cada actividad
- Elaborar cada actividad en un issue de github y agregar en comentarios todo el research (tutoriales, ligas etc.)

**Comment by ivanchenoweth** [comment]
Sugiero cambiar nombre al proyecto, y elaborar un diagrama de flujo de datos simple para conocer los procesos.

**Comment by ivanchenoweth** [comment]
Aqui esta como elaborar un diagrama de flujo de datos para identificar los procesos.
https://es.wikipedia.org/wiki/Diagrama_de_flujo_de_datos

**Comment by JEstebanSanti** [comment]
# Revisión  Plan De Proyecto 😊 
@ivanchenoweth favor de hacer revisión del documento del plan del proyecto maestro para concluir con el issue👍 
https://docs.google.com/document/d/1aod4ic8SLyPRHFxcZQ-4T4Og4293dxJIqiMgy0fxw0w/edit?usp=sharing

**Comment by ivanchenoweth** [comment]
> # Revisión Plan De Proyecto 😊
> @ivanchenoweth favor de hacer revisión del documento del plan del proyecto maestro para concluir con el issue👍 https://docs.google.com/document/d/1aod4ic8SLyPRHFxcZQ-4T4Og4293dxJIqiMgy0fxw0w/edit?usp=sharing

Ok gracias. 
Les hice obervaciones en classrrom ... tambien aqui se las copio.

Esta muy bien el borrador de esta actividad.
Yo lo evaluaria como DE en los criterios, porque considero que puede quedar mas enriquecido el punto de la propuesta (pirchdeck). Yo no les he puesto reuerimientos, ni tampoco uds. tienen porque colocarlos, puderan siemplemente mencionar las funcionalidades y beneficios al usuario.
Considero que agregando un poco de analisis de la competencia y el posible modelo de negocios que pueda funcionar.
https://www.thepowermba.com/es/blog/que-es-pitch-deck
