### ISSUE TITLE
20 - Login 

### ISSUE THREAD

**Issue by ivanchenoweth** [REUBATCODE/UP-HEALTH#4]
Elaborar una pagina de login PHP o HTML

**Comment by ivanchenoweth** [comment]
Ejemplo de LOGIN con sesiones
https://www.w3schools.blog/php-program-to-create-login-and-logout-using-sessions

**Comment by ivanchenoweth** [comment]
https://www.youtube.com/watch?v=7zGXnGvHc7s

**Comment by ivanchenoweth** [comment]
- Recurso 
Login y logout usando sesiones
https://www.w3schools.blog/php-program-to-create-login-and-logout-using-sessions

**Comment by ivanchenoweth** [comment]
- Recurso 
- https://github.com/kunalbagnial/PHP-MySQL-Login-System

**Comment by ivanchenoweth** [comment]
- Reurso
https://www.youtube.com/watch?v=c3GoigQ5vRE&list=PLAFTVct4TDOa1HHObYNcGqRXsYTcCnfF4&ab_channel=MagtimusPro

**Comment by ivanchenoweth** [comment]
Cuantas PoCs de entrenamiento se han hecho? Que resultados se tienen?

**Comment by JEstebanSanti** [comment]
- propuestas de diseño de ui y colores
- @AngelDabnee @RUBENBERNARDO 
![form-login](https://github.com/REUBATCODE/UP-HEALTH/assets/78988823/26751752-ff81-4891-a7d0-32f5f6aadfb2)
![registro-login](https://github.com/REUBATCODE/UP-HEALTH/assets/78988823/1e234f9c-bd98-4ebe-a782-0497414dec9a)

**Comment by AngelDabnee** [comment]
los amé bro

**Comment by ivanchenoweth** [comment]
Es necesario hacer un pull request de esta rama con las propuestas, y las pruebas en caso de haberlas

**Comment by ivanchenoweth** [comment]
> 

A quien amaste bro?

**Comment by ivanchenoweth** [comment]
Cuando quieran respuesta rapida, pueden etiquetarme @ivanchenoweth
