### ISSUE TITLE
30 - Crud de usuarios para usuario administrador

### ISSUE THREAD

**Issue by ivanchenoweth** [REUBATCODE/UP-HEALTH#5]
- Recurso
https://www.youtube.com/watch?v=v_wlLqN1IV4&ab_channel=WebDeveloperUrianViera
https://github.com/urian121/CRUD-con-PHP-MYSQL-y-BOOTSTRAP_5

**Comment by JEstebanSanti** [comment]
# propuesta de ui para crud create admin y login admin

-  **CRUD CREATE** pantalla para crear nuevo usuario admin
![Registr-create-admin](https://github.com/REUBATCODE/PROYECTO-INTEGRADORA/assets/78988823/fbb17c70-1199-48c2-9747-b970bed5325e)

- **Login Admin Users**
![Login-admin](https://github.com/REUBATCODE/PROYECTO-INTEGRADORA/assets/78988823/aa6e49f9-b901-4b5f-a4ed-09364e71d07d)

**Comment by REUBATCODE** [comment]
Me gusta mucho el diseño

**Comment by JEstebanSanti** [comment]
![Image](https://github.com/REUBATCODE/UP-HEALTH/assets/78988823/12f1471b-8881-4652-a72d-85ce71385a8e)
![Image](https://github.com/REUBATCODE/UP-HEALTH/assets/78988823/7dc9a3b4-700e-480e-8d1f-0a03ff5e3411)
![Image](https://github.com/REUBATCODE/UP-HEALTH/assets/78988823/a55eab1f-3a86-41d6-9eaa-931322d7a0ee)

**Comment by JEstebanSanti** [comment]
- **pantallas que me faltaban en la propuesta de UI**
- hay dos versiones de la pantalla que lista usuarios admin una con solo 3 botones y otra con 2 botones en cada row 
- voten y comenten cual de las dos les parece mejor
- @REUBATCODE  @ivanchenoweth  @RUBENBERNARDO

**Comment by ivanchenoweth** [comment]
Hay qye hacer los pull request
