### ISSUE TITLE
35 - Dashboard o pantalla inicial de administrador

### ISSUE THREAD

**Issue by REUBATCODE** [REUBATCODE/UP-HEALTH#6]
Diseñar la pantalla inicial de administrador

**Comment by ivanchenoweth** [comment]
Que impedimento hay para elaborar este issue, ya tiene 5 dias

**Comment by AngelDabnee** [comment]
![Image](https://github.com/REUBATCODE/PROYECTO-INTEGRADORA/assets/114833669/a8bc7832-b968-40b1-8571-4ee206579307)

**Comment by ivanchenoweth** [comment]
No existe un PR de esta historia

**Comment by ivanchenoweth** [comment]
Todavia no hay PR

**Comment by JEstebanSanti** [comment]
este issue ya se hizo y ya esta en la rama dev
